name: "Check licenses"
description: ""
author: ""

inputs:
  project_license:
    description: "License type (MIT, Apache-2.0)"
    required: true
  working_directory:
    description: "Working directory"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.project_license }}
    - ${{ inputs.working_directory }}